import Head from 'next/head'
import { Inter } from 'next/font/google'
import Codespace from '@/components/codemirror'




export default function Home() {
  const array = [
    {init: "console.log('hi1')",name: 'one', output: 'qwertyuio'},
    {init: "console.log('hi2')",name: 'two', output: 'qwertyuio'},
    {init: "console.log('hi3')",name: 'three', output: 'qwertyuio'},
    {init: "console.log('hi4')",name: 'four', output: 'qwertyuio'},
    {init: "console.log('hi5')",name: 'five', output: 'qwertyuio'},
    {init: "console.log('hi6')",name: 'six', output: 'qwertyuio'},
  ]

  return (
    <>
      <Head>
        <title>Scripter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-vh-100 pb-5 text-white'>
        <header className='container d-flex flex-column align-items-start'>
          <h1><i className="bi bi-code"/></h1>
          <h1>Scripter</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid ullam impedit maxime ad libero aperiam.</p>
        </header>
        <div className='container d-flex flex-column gap-5'>
          
        {array.map((e)=>(
          <Codespace data={e} />
        ))}
      
        </div>
      </main>
    </>
  )
}
