import Head from 'next/head'
import { Inter } from 'next/font/google'
import Codespace from '@/components/codemirror'




export default function Home() {
  

  return (
    <>
      <Head>
        <title>Scripter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-vh-100 pb-5 text-white'>
        <header className='container d-flex flex-column align-items-start'>
          <h1><i className="bi bi-code"/></h1>
          <h1>Untitled</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid ullam impedit maxime ad libero aperiam.</p>
        </header>
        <div className='container d-flex flex-column gap-5'>
          <Codespace init="hello" name="one" output="hello" />
          <Codespace init="hello" name="one" output="hello" />
          <Codespace init="hello" name="one" output="hello" />
          <Codespace init="hello" name="one" output="hello" />
          <Codespace init="hello" name="one" output="hello" />
          <Codespace init="hello" name="one" output="hello" />
      
        </div>
      </main>
    </>
  )
}
